# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "transtape-checkout"
client_id = "1696e2861b10e95eeebbb010d9fcae54"
application_url = "https://shopify.dev/apps/default-app-home"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = ""

[auth]
redirect_urls = [ "https://shopify.dev/apps/default-app-home/api/auth" ]

[webhooks]
api_version = "2024-01"

[pos]
embedded = false
